Enhanced giraph-debug to give better error msg
when a bogus mode is passed, e.g., `./giraph-debug hui` instead of `gui`.

diff --git a/giraph-debug b/giraph-debug
--- a/giraph-debug
+++ b/giraph-debug
@@ -86,7 +86,7 @@ fi
 
 Here=$(cd "$(dirname "$0")" && pwd -P)
 jars=($Here/target/giraph-debugger-*.jar)
-[ -e "${jars[0]}" ] || error "Cannot find giraph-debugger JAR"
+[ -e "${jars[0]}" ] || error "Cannot find giraph-debugger JAR" # TODO check CLASSPATH before failing
 CLASSPATH="${CLASSPATH:+$CLASSPATH:}$(IFS=:; echo "${jars[*]}"):$(hadoop classpath)"
 javaOpts=(
     -D"giraph.debugger.traceRootAtHDFS=$TRACE_ROOT" # pass the TRACE_ROOT at HDFS
@@ -172,6 +172,8 @@ done
 shift $(($OPTIND - 1))
 
 # parse arguments
+[ $# -gt 2 ] ||
+    usage "giraph-debug $1: Unrecognized mode"
 debugConfigClassName=$1; shift
 if [ -f "$debugConfigClassName" ]; then
     # the DebugConfig class name is optional, and
@@ -180,6 +182,8 @@ if [ -f "$debugConfigClassName" ]; then
     debugConfigClassName=org.apache.giraph.debugger.DebugConfig
 else
     jarFile=$1; shift
+    [ -f "$jarFile" ] ||
+        error "$jarFile: Not an existing jar file"
 fi
 giraphRunnerClass=$1
 case $giraphRunnerClass in
