Parameterized TRACE_ROOT
so it can be consistently configured through environment variable.

diff --git a/backend/giraph-debug b/backend/giraph-debug
--- a/backend/giraph-debug
+++ b/backend/giraph-debug
@@ -13,6 +13,10 @@
 #         JAR_FILE org.apache.giraph.GiraphRunner [HADOOP_OPTS] \
 #         COMPUTATION_CLASS GIRAPH_RUNNER_ARGS...
 # 
+# By default all trace data for debugging will be stored under
+# /giraph-debug-trace/ at HDFS.  To change this path set the environment
+# variable TRACE_ROOT to the desired path.
+# 
 # 
 # To list available traces for a Giraph job, run the following command:
 # 
@@ -38,17 +42,23 @@
 #     giraph-debug gui [PORT]
 # 
 # and open the URL in your web browser.
+# 
 #
 # Author: Jaeho Shin <netj@cs.stanford.edu>
 # Created: 2014-05-09
 set -eu
 
-# show usage unless we have enough arguments
+# some defaults
+: ${TRACE_ROOT:=/giraph-debug-traces} # HDFS path to where the traces are stored
+: ${CLASSNAME_SUFFIX:=Original}       # A suffix for user computation class used by instrumenter
+
 error() { echo >&2 "$@"; false; }
 usage() {
     sed -n '2,/^#$/ s/^# //p' <"$0"
     [ $# -eq 0 ] || error "$@"
 }
+
+# show usage unless we have enough arguments
 if [ $# -lt 1 ]; then
     usage
     exit 1
@@ -56,11 +66,13 @@ fi
 
 Here=$(cd "$(dirname "$0")" && pwd -P)
 jars=($Here/target/backend-*.jar)
+[ -e "${jars[0]}" ] || error "Cannot find giraph-debugger JAR"
 CLASSPATH="${CLASSPATH:+$CLASSPATH:}$(IFS=:; echo "${jars[*]}")"
-exec_java() {
-    exec java ${CLASSPATH:+-cp "$CLASSPATH"} \
-        "$@"
-}
+javaOpts=(
+    -cp "$CLASSPATH"
+    -D"giraph.debugger.traceRootAtHDFS=$TRACE_ROOT" # pass the TRACE_ROOT at HDFS
+)
+exec_java() { exec java "${javaOpts[@]}" "$@"; }
 
 # handle modes other than launching GiraphJob first
 case $1 in
@@ -77,8 +89,13 @@ case $1 in
         shift
         [ $# -gt 0 ] || usage "JOB_ID to list is missing"
         JobId=$1; shift
-        exec_java stanford.infolab.debugger.commands.ListTraces \
-            "$JobId" "$@"
+        # XXX Relying on hadoop fs -ls instead
+        #exec_java stanford.infolab.debugger.commands.ListTraces \
+        #    "$JobId" "$@"
+        set -o pipefail
+        hadoop fs -lsr "$TRACE_ROOT"/"$JobId" |
+        sed "s#.* $TRACE_ROOT/$JobId/##"
+        exit
         ;;
 
     dump)
@@ -126,6 +143,7 @@ esac
 # skip hadoop jar options
 hadoopJarOpts=(
 $giraphRunnerClass
+"${javaOpts[@]}"
 -D dbgcfg="$debugConfigClassName" # pass the class name for debug configuration
 )
 while shift; do
@@ -143,11 +161,11 @@ origClassName=$1; shift
 export HADOOP_CLASSPATH="${HADOOP_CLASSPATH:+$HADOOP_CLASSPATH:}$jarFile"
 
 # first, instrument the given class
-classNameSuffix=Original
+classNameSuffix=$CLASSNAME_SUFFIX
 tmpDir=$(mktemp -d "${TMPDIR:-/tmp}/giraph-debug.XXXXXX")
 trap 'rm -rf "$tmpDir"' EXIT
 java -cp "$HADOOP_CLASSPATH${CLASSPATH:+:$CLASSPATH}" \
-    -Dgiraph.debugger.classNameSuffix="$classNameSuffix" \
+    -D"giraph.debugger.classNameSuffix=$classNameSuffix" \
     stanford.infolab.debugger.instrumenter.InstrumentGiraphComputationClasses \
         "$origClassName" "$tmpDir"/classes
 instrumentedClassName="$origClassName"
